version: "latest"

services:

  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
      
  db:
    container_name: postgres
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres:/data/postgres