version: "latest"

services:

  api:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    env_file:
      - .env
    command: npm run start:dev
      
  db:
    container_name: postgres
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: "admin"
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: